export const screens = {
  DASHBOARD: 'DASHBOARD',
  HOME: 'HOME',
  CATEGORY_PRODUCTS: 'CATEGORY_PRODUCTS',
  ALL_PRODUCTS: 'ALL_PRODUCTS',
  PROFILE: 'PROFILE',
  CART: 'CART',
  CATEGORY: 'CATEGORY',
  PRODUCT_DETAILS: 'PRODUCT_DETAILS',
};
